[manifest]
version = "1.0.1s"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''check_and_set_high_score('hand',  SMODS.calculate_round_score() )'''
position = "before"
payload = '''
record_history_hands({text = text, disp_handname = non_loc_disp_text, chips = hand_chips, mult = mult, scoring_hand = scoring_hand})

'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local high_scores = UIBox_button{ label = {localize('b_stats')}, button = "high_scores", minw = 5}'''
position = "after"
payload = '''
if G.STAGE == G.STAGES.RUN then 
    high_scores = {n=G.UIT.R, config={align = "cm", padding = 0.05}, nodes={
        {n=G.UIT.C, config={align = "cm", padding = 0}, nodes={
            UIBox_button{ label = {localize('b_stats')}, button = "high_scores", minw = 2.44},
        }},
        {n=G.UIT.C, config={align = "cm", padding = 0, minw = 0.05}, nodes={}},
        {n=G.UIT.C, config={align = "cm", padding = 0}, nodes={
            UIBox_button{ label = {localize('b_quick_load')}, button = "quick_load", minw = 2.44}
        }},
    }}
else
    high_scores = {n=G.UIT.R, config={align = "cm", padding = 0.05}, nodes={
        {n=G.UIT.C, config={align = "cm", padding = 0}, nodes={
            UIBox_button{ label = {localize('b_stats')}, button = "high_scores", minw = 2.44},
        }},
        {n=G.UIT.C, config={align = "cm", padding = 0, minw = 0.05}, nodes={}},
        {n=G.UIT.C, config={align = "cm", padding = 0}, nodes={
            UIBox_button{ label = {localize('k_achievement')}, button = "achievement_list", minw = 2.44}
        }},
    }}
end
'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''--check the hand first'''
position = "before"
payload = '''
    G.GAME.preview.dollar_tran = 0
'''
match_indent = false
overwrite = false

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''G.E_MANAGER:add_event(Event({func = (function() G.GAME.dollar_buffer = 0; return true end)}))'''
position = "at"
payload = '''
if Portable.config.reduce_animation then
    G.GAME.dollar_buffer = 0
else
    G.E_MANAGER:add_event(Event({func = (function() G.GAME.dollar_buffer = 0; return true end)}))
end
'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''G.hand:sort('desc')'''
position = "before"
payload = '''
    if Portable.config.flip_sort then
        for k, v in ipairs(G.hand.cards) do
            if v.facing == 'back' then v:flip() end
        end
        for k, v in ipairs(G.jokers.cards) do
            if v.facing == 'back' then v:flip() end
        end
    end
'''
match_indent = false
overwrite = false

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''G.hand:sort('suit desc')'''
position = "before"
payload = '''
    if Portable.config.flip_sort then
        for k, v in ipairs(G.hand.cards) do
            if v.facing == 'back' then v:flip() end
        end
        for k, v in ipairs(G.jokers.cards) do
            if v.facing == 'back' then v:flip() end
        end
    end
'''
match_indent = false
overwrite = false

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''if G.ROOM then'''
position = "before"
payload = '''
    if Portable.config.zoom_out then
        G.TILESCALE = G.TILESCALE * 0.9
    end

'''
match_indent = false
overwrite = false

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''G.ROOM_ATTACH.T.h = G.TILE_H'''
position = "after"
payload = '''
    if Portable.config.zoom_out then
        G.ROOM.T.x = math.max(G.ROOM_PADDING_W,
			(w / (G.TILESIZE * G.TILESCALE) - G.ROOM.T.w) / 2)
		G.ROOM.T.y = math.max(G.ROOM_PADDING_H,
			(h / (G.TILESIZE * G.TILESCALE) - G.ROOM.T.h) / 2)
    else
        if w/h < G.window_prev.orig_ratio then
			G.ROOM.T.x = G.ROOM_PADDING_W
			G.ROOM.T.y = (h/(G.TILESIZE*G.TILESCALE) - (G.ROOM.T.h+G.ROOM_PADDING_H))/2 + G.ROOM_PADDING_H/2
		else
			G.ROOM.T.y = G.ROOM_PADDING_H
			G.ROOM.T.x = (w/(G.TILESIZE*G.TILESCALE) - (G.ROOM.T.w+G.ROOM_PADDING_W))/2 + G.ROOM_PADDING_W/2
		end
    end
--[[
'''
match_indent = false
overwrite = false

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''G.ROOM_ORIG = {'''
position = "before"
payload = '''
]]
'''
match_indent = false
overwrite = false
